### ISSUE TITLE
Traffic classification missing for upload

### ISSUE THREAD

**Issue by gnuton** [gnuton/asuswrt-merlin.ng#106]
**Firmware Version Affected **
386.3-alpha1

**Is this bug present in upstream Merlin releases too?**
No

**Describe the bug**
![image](https://user-images.githubusercontent.com/576580/120044100-77af0a00-c00d-11eb-9d1b-da48fbb84ee5.png)

**To Reproduce**
1. Activate Adaptive QoS
2. go to classification page
3. see upload is empty

**Comment by gnuton** [comment]
to fix we may need to track a different interface:
- eth0 - currently the default option
- ptm0  - tested, not good
- wan0 - under testing.
- eth4 - default on rt-ax58u and possible choice

**Comment by bake-73** [comment]
Could this be the problem with cake?

**Comment by bake-73** [comment]
Is this fixed in the new version?
Thanks

**Comment by gnuton** [comment]
no this is not fixed yet. It's not realated to cake, I do still to get how this really works

**Comment by gnuton** [comment]
Tried this again and actually ptm0 worked (-_-) from what I have seen there was not other options.

**Comment by gnuton** [comment]
The fix will be part from the next beta 6.
