### ISSUE TITLE
Missing firmware manual upload section

### ISSUE THREAD

**Issue by DaveEzrakhovich** [gnuton/asuswrt-merlin.ng#477]
**Router Model Affected**
Models: DSL-AX82U / DSL-AX5400

**Firmware Version Affected**
388.1-gnuton1

**Is this bug present in upstream Merlin releases too?**
No

**Describe the bug**
After the new version was released, I was notified that I could update it.
I went to the firmware section in the router UI portal, but the upload options were missing. 

**To Reproduce**
1. Go to 'Administration'
2. Click on 'Firmware Upgrade' section at the top

**Expected behavior**
Option to upload the firmware. 

**Screenshots**
![Screenshot 2023-10-06 135232](https://github.com/gnuton/asuswrt-merlin.ng/assets/8363616/512d7792-0a1e-4329-8b88-abb5b0d716ea)

**Notes**
I've been using the gunton builds for several years without any issues, this specific device was upgraded several times in the past.

**Comment by gnuton** [comment]
there could be a regression which was already fixed once https://github.com/gnuton/asuswrt-merlin.ng/issues/144
I will check. In any case thisi for an old firmware. You should upgrade to the last one.
To make show the upgrade option you have to trick chrome

**Comment by DaveEzrakhovich** [comment]
Thanks, @gnuton. I've upgraded to the newest version using browser debug
But the problem still exists in the 3004.388.4_0-gnuton1 version 

Anyway, if other users have the same issue, here is the browser quick fix that will allow you to upgrade 

1. Open the router admin page + login 
2. Go to administration -> firmware upgrade 
3. Open dev tools (F12 or right-click and click inspect) 
4. Go to the sources tab and add a breakpoint on the line with "var exist_update = 0;" 
5. refresh the page
6. Go to the console tab and run the following: no_fw_manual_support = 0; exist_update = 1; no_update_support = 0; 
7. Press resume (F8)
8. Upload the firmware and good luck

**Comment by Jsonmess** [comment]
i try the last version 3004.388.6_0-gnuton1 in dsl_5400/ds_82u,this issue is still exit； @gnuton

**Comment by gnuton** [comment]
Do you have a sort of branded router?

**Comment by dave-aspecto** [comment]
Nope native
The issue happened on a couple of versions, but as the workaround works I didn't say anything 😅

**Comment by DaveEzrakhovich** [comment]
> Do you have a sort of branded router?

Nope native
The issue happened on a couple of versions, but as the workaround works I didn't say anything 😅

**Comment by minnows** [comment]
Seems problem is not fixed in new version? 

<img width="977" height="672" alt="Image" src="https://github.com/user-attachments/assets/c968e2cb-5e07-4ee0-863e-e706a88c0cb7" />

**Comment by gnuton** [comment]
Please test the images here https://github.com/gnuton/asuswrt-merlin.ng/pull/970 if fine I will merge.

**Comment by gnuton** [comment]
any feedback? @DaveEzrakhovich ?
