### ISSUE TITLE
Firmware Upgrade page Current Version details change seconds after page load.

### ISSUE THREAD

**Issue by Yakumounr** [gnuton/asuswrt-merlin.ng#480]
**Router Model Affected**
Models:  DSL-AX82U

**Firmware Version Affected**
3004.388.4_0-gnuton0_beta2

**Is this bug present in upstream Merlin releases too?**
Unknown

**Describe the bug**
A weird quirk on the Firmware Upgrade page, Current Version shown loads initially as "3004.388.4_0-gnuton0_beta2", approximately four seconds afterwards with no user interaction needed it pops into "3004.388.4-gnuton0_beta2" dropping the "_0" for some reason.
Tested on Chrome and Firefox.

**To Reproduce**
1. Go to 'Administration' from the left menu
2. Click on 'Firmware Upgrade' tab.
4. Note the Current Version displayed
5. Wait 4+ seconds, note any change

**Expected behavior**
Firmware version information should stay consistent.

**Comment by Katana1074** [comment]
I can confirm this bug......

Router Model Affected
Models: DSL-AX82U

Firmware Version Affected
3004.388.4_0-gnuton0_beta2

**Comment by gnuton** [comment]
Fixed in the stable

**Comment by Yakumounr** [comment]
It still happens in the stable release
"3004.388.4_0-gnuton1" is changing to "3004.388.4-gnuton1"
