### ISSUE TITLE
DST not working on 386.00_0-gnuton0_alpha9

### ISSUE THREAD

**Issue by tarobun** [gnuton/asuswrt-merlin.ng#68]
**Firmware Version Affected **
386.00_0-gnuton0_alpha9

**Is this bug present in upstream Merlin releases too?**
Dunno

**Describe the bug**
TimeZone is : (GMT+10) Canberra, Melbourne, Sydney
DST is set to start month 10, 1st Sunday and end month 4, 1st Sunday

System Time does not have DST applied and get a reminder that "The System time zone is different is different from your locale setting."

**To Reproduce**
1. Go to 'Advance Settings -> Administration'
2. Scroll down to 'Basic Config'
3. Set 'TimeZone' to '(GMT+10) Canberra, Melbourne, Sydney'
4. Set 'DST time zone changes starts' to '10' month '1st' 'Sun' Week & days '2' hours
5. Set 'DST time zone changes ends' to '4' month '1st' 'Sun' Week & days '3' hours
4. See warning '* Reminder: The System time zone is different from your locale setting.'
5. Go to 'Advance Settings -> System Log'
6. See System Time msg - '* Daylight savings time is enabled in this time zone.' but time does not have DST applied.

**Expected behavior**
DST applied and no warning as local time matches router time.

**Screenshots**
<img width="747" alt="DST bug" src="https://user-images.githubusercontent.com/2762558/104380928-dd7b8780-557f-11eb-8980-9a6a888f63ba.png">

<img width="758" alt="System Time" src="https://user-images.githubusercontent.com/2762558/104382778-d99d3480-5582-11eb-9c8c-f4885f0bf01c.png">

<img width="251" alt="Current Time" src="https://user-images.githubusercontent.com/2762558/104382902-15d09500-5583-11eb-90ca-889411b26129.png">

**Comment by gnuton** [comment]
This has been fixed. The fix will be part of the next pre-release (beta2)
![image](https://user-images.githubusercontent.com/576580/108140207-e7823000-70c1-11eb-9535-19f414cdf3b8.png)

**Comment by gnuton** [comment]
I will keep this open until this is not verified for AX82U too.

**Comment by gnuton** [comment]
This has been fixed for DSL-AX82U with the 386.1_2-beta2

**Comment by tarobun** [comment]
This is still not working for me in beta3.

I think this commit fixes it - https://github.com/RMerl/asuswrt-merlin.ng/pull/701

**Comment by tarobun** [comment]
Works with 386.02_1-gnuton0_alpha1

**Comment by gnuton** [comment]
Cool thanks for testting it out! I can close this issue then! :D
